invertase/stripe-firebase-extensions

firestore-stripe-invoices/extension.yaml
firestore-stripe-subscriptions/extension.yaml

Fixes #28 
- Firestore collection paths must be an odd number of segments separated by slashes, e.g. "path/to/collection".

chore(*): Validate Cloud Firestore collection paths input.

---

firestore-stripe-subscriptions/CHANGELOG.md
firestore-stripe-subscriptions/POSTINSTALL.md

Fixes #47 
[fix] - Fix security rules example in `POSTINSTALL.md`. (#47)

fix(firestore-stripe-subscriptions): More secure security rules example.

---

firestore-stripe-invoices/extension.yaml
firestore-stripe-invoices/functions/package.json
firestore-stripe-subscriptions/extension.yaml
firestore-stripe-subscriptions/functions/package.json

Cloud Functions [v3.8.0](https://github.com/firebase/firebase-functions/releases/tag/v3.8.0) and [v3.9.0](https://github.com/firebase/firebase-functions/releases/tag/v3.9.0) combined have added support for a total of 11 new regions.
This PR should add support for these regions :)
Equivalent PR on the 1st party extensions: https://github.com/firebase/extensions/pull/388

chore(*): add new cloud functions locations

---

firestore-stripe-subscriptions/CHANGELOG.md

Remove beta note as Checkout now supports all billing pricing models.

chore(firestore-stripe-subscriptions): remove-beta-note

---

firestore-stripe-invoices/extension.yaml
firestore-stripe-invoices/functions/package.json
firestore-stripe-subscriptions/extension.yaml
firestore-stripe-subscriptions/functions/package.json

`firebase-functions` 3.14.1 introduces a new Cloud Function location: `Warsaw (europe-central2)`
This PR should:
- update `firebase-admin` to 9.9.0
- update `firebase-functions` to 3.14.1
- add the new location to the list of locations that developers can choose from when configuring the extensions.

refactor(*): add Warsaw Cloud Function Location

---

.github/workflows/validate.yml

Adds start of CI to validate TS builds and formatting - via GitHub Actions.

ci: add validation job

---

.github/workflows/test.yml
firestore-stripe-web-sdk/.gitignore
firestore-stripe-web-sdk/etc/firestore-stripe-payments-js.api.md
firestore-stripe-web-sdk/package.json
firestore-stripe-web-sdk/src/index.ts
firestore-stripe-web-sdk/src/init.ts
firestore-stripe-web-sdk/src/product.ts
firestore-stripe-web-sdk/src/utils.ts
firestore-stripe-web-sdk/test/init.spec.ts
firestore-stripe-web-sdk/test/product.spec.ts

Adding the above APIs, where `getProduct()` reads the product information from Firestore. I'm introducing an internal `ProductDAO` interface that handles all database interactions. This allows us to easily unit test the SDK via fakes and mocks. In order to unit test the actual Firestore interactions, I'm using the Firebase emulator suite.
Additionally, I'm removing the `npm run build` step from the CI workflow, since it's already tied to a post-install hook, and runs as part of `npm i`.

feat: Added Product, Price and getProduct APIs

---

firestore-stripe-invoices/functions/src/index.ts
firestore-stripe-subscriptions/functions/src/index.ts
firestore-stripe-web-sdk/.mocharc.js
firestore-stripe-web-sdk/etc/firestore-stripe-payments-js.api.md
firestore-stripe-web-sdk/package.json
firestore-stripe-web-sdk/src/index.ts
firestore-stripe-web-sdk/src/init.ts
firestore-stripe-web-sdk/src/product.ts
firestore-stripe-web-sdk/src/session.ts
firestore-stripe-web-sdk/src/utils.ts
firestore-stripe-web-sdk/test/emulator.spec.ts
firestore-stripe-web-sdk/test/product.spec.ts
firestore-stripe-web-sdk/test/session.spec.ts
package.json

Added `createCheckoutSession()` API. To keep this PR simple, I'm only adding a few of the parameters supported.
I'm also renaming the integration test suite file to `emulator.spec.ts`, and using it to place all integration tests for now. In a future PR I might move it to a separate directory separate from unit tests, and split it into a bunch of smaller files.
I also had to upgrade prettier to the latest version since the old version did not support logical nullish assignment operator (`??=`), which I wanted to use in my code. Couple of other source files in the repo also got slightly updated as a result.

feat: Added createCheckoutSession() API

---

firestore-stripe-web-sdk/etc/firestore-stripe-payments-js.api.md
firestore-stripe-web-sdk/src/index.ts
firestore-stripe-web-sdk/src/init.ts
firestore-stripe-web-sdk/src/session.ts
firestore-stripe-web-sdk/src/user.ts
firestore-stripe-web-sdk/test/emulator.spec.ts
firestore-stripe-web-sdk/test/session.spec.ts

Added support for passing a timeout to the `createCheckoutSession()` function. Defaults to 30 seconds.
Also the `FirestoreSessionDAO` class currently deals with checking current user session. Since this logic is required in several other places, I'm refactoring it into a new `UserDAO` interface.

feat: Added support for configurable timeouts

---

firestore-stripe-invoices/extension.yaml
firestore-stripe-subscriptions/extension.yaml

Upcoming changes will allow a secret type to define secrets and passwords. This adds the type to all instances of the Stripe Api key / web-hook configuration

feat(*) added new secret param type for ext config

---

firestore-stripe-web-sdk/karma.conf.js
firestore-stripe-web-sdk/package.json
firestore-stripe-web-sdk/test/emulator.spec.ts
firestore-stripe-web-sdk/webpack.test.js

We currently run tests using mocha (nodejs) + jsdom to emulate a browser environment. It loads the Nodejs version of the Firestore SDK which throws `TypeError: Invalid URL: index.node.cjs.js` because jsdom confuses it to think it's executing in a browser.
The PR changes the tests to run in a real browser (chrome) to workaround this issue, and it's a more reliable test setup because tests will execute in the same environment where the SDK will be used.

chore: Run tests in real browser

---

firestore-stripe-web-sdk/README.md

Changing to a absolute URL, so it will work correctly when rendered outside github too (e.g. https://www.npmjs.com/package/@stripe/firestore-stripe-payments)

chore: Changed API ref link to an absolute URL

---

firestore-stripe-web-sdk/src/init.ts

It turns out Firebase JS SDK doesn't support registering scoped package names:
```
@firebase/app:', 'Unable to register library "@stripe/firestore-stripe-payments" with version "__VERSION__": library name "@stripe/firestore-stripe-payments" contains illegal characters (whitespace or "/")'
```
I'm shortening the package name to the unscoped part.

fix: Registering correct package name

---

firestore-stripe-web-sdk/etc/firestore-stripe-payments.api.md
firestore-stripe-web-sdk/src/index.ts
firestore-stripe-web-sdk/src/payment.ts
firestore-stripe-web-sdk/test/emulator.spec.ts
firestore-stripe-web-sdk/test/payment.spec.ts
firestore-stripe-web-sdk/test/testdata.ts

Adding support for fetching one-time payment records from Firestore. Starting with the `Payment` type and the `getCurrentUserPayment()` function.

feat: Added Payment and getCurrentUserPayment APIs

---

firestore-stripe-web-sdk/etc/firestore-stripe-payments.api.md
firestore-stripe-web-sdk/src/index.ts
firestore-stripe-web-sdk/src/payment.ts
firestore-stripe-web-sdk/test/emulator.spec.ts
firestore-stripe-web-sdk/test/payment.spec.ts
firestore-stripe-web-sdk/test/testdata.ts

* Added `getCurrentUserPayments()` function to fetch multiple one-time payments from Firestore.
* Renamed `PaymentState` to `PaymentStatus` for consistency with `SubscriptionStatus`.

feat: Added getCurrentUserPayments API

---

firestore-stripe-web-sdk/etc/firestore-stripe-payments.api.md
firestore-stripe-web-sdk/src/index.ts
firestore-stripe-web-sdk/src/payment.ts
firestore-stripe-web-sdk/test/emulator.spec.ts
firestore-stripe-web-sdk/test/payment.spec.ts

- Add `onCurrentUserPaymentUpdate()` API
- Add unit tests and emulator tests
Note: this change is tracking the `payments-api` feature branch.

feat(firestore-stripe-web-sdk): Added onCurrentUserPaymentUpdate() API

---

firestore-stripe-invoices/extension.yaml

An installation error occurs on the `firestore-stripe-invoices` extension. 
```
generic::invalid_argument: extension.yaml is invalid: generic::invalid_argument: Request had 2 validation errors: `spec.externalServices.0`: ExternalService must specify `pricingUri`; `spec.externalServices.1`: ExternalService must specify `name`.
```
This PR updates the `pricingUri` to the correct value in the extensions yaml configuration.

fix(firestore-stripe-invoices): updated external services 

---

firestore-stripe-invoices/extension.yaml

When installing the `firestore-stripe-invoices` a non numeric value could be added as a value.
This PR adds validation to ensure only numerical values can be added during the installation process.

chore(firestore-stripe-invoices): added validation for payment due days.

---

firestore-stripe-payments/PREINSTALL.md
firestore-stripe-payments/extension.yaml
firestore-stripe-payments/functions/jest.config.js
firestore-stripe-payments/functions/package.json
firestore-stripe-payments/functions/src/index.ts
firestore-stripe-payments/functions/tsconfig.json
package.json

`Eventarc` events are now available in the latest firebase-admin sdk.
This PR adds a feature to omit an event based on Stripe event sent through the extensions web-hook.

feat(firestore-stripe-payments): added stripe extension events

---

firestore-stripe-payments/functions/__tests__/run-script-watch.ts
firestore-stripe-payments/functions/__tests__/tsconfig.json
firestore-stripe-payments/functions/package.json
firestore-stripe-payments/runTests.sh
firestore-stripe-web-sdk/package.json

chore(firestore-stripe-payments): updated scripts for CI and local testing

---

firestore-stripe-payments/README.md

Prices API replaces the Plans API, per https://stripe.com/docs/api/plans
> You can now model subscriptions more flexibly using the [Prices API](https://stripe.com/docs/api/coupons#prices). It replaces the Plans API and is backwards compatible to simplify your migration.
In the Stripe dashboard when making a restricted key, there is no option for "Plans". It seems to me that the "Prices" resource should be used instead.

docs(firestore-stripe-payments): Update APIs for restricted key

---

firestore-stripe-payments/functions/src/index.ts

This PR does two small things to the `createPortalLink` cloud function.
1. Throws 'unauthenticated' code instead of 'failed-precondition' in response to unauthenticated requests. Not a huge problem but the `unauthenticated` `HttpsError` code is provided by Firebase specifically for this purpose.
2. Uses optional chaining (supported in Node 14) to avoid redundant check for `context.auth.uid`. Also not a big deal but it's nice to avoid the extra conditional that could needlessly throw a generic error.

feat(firestore-stripe-payments): createPortalLink auth tweaks

---

firestore-stripe-payments/extension.yaml

The us-west1 region is missing from the list of regions for applying for the stripe extension.

feat: Add us-west1 as deployable function region

---

firestore-stripe-payments/CHANGELOG.md
firestore-stripe-payments/extension.yaml
firestore-stripe-payments/functions/src/index.ts

* `firestore-stripe-payments@0.3.2` (477ceef1272c7d2a48afecdc82bc5146bf7043dc).

chore: 2022-11-30 release

---

firestore-stripe-payments/functions/src/index.ts

In case where the Invoice has no associated Payment Intent, the Firestore collection write would fail.
This PR fixes this by deferring the the `invoice.id` if no Payment Intent when writing to the Firestore collection.
Fixes #505, #368

fix(firestore-stripe-payments): Address issue where `insertInvoiceRecord` function fails

---

firestore-stripe-web-sdk/README.md

There is a common mistake in README which uses `in` iterator instead of `of`.

Fix typo in README.md

---

firestore-stripe-payments/functions/src/index.ts

This comments refers to a subcollection on subscription doc, but I think it should ref to the customer doc.
We aren't writing to subscription, but to customer. 
This came up because I'm not using subscriptions but do want to use this to sync payments on one-time purchases (via checkout_session and/or manual invoices)
Overall, it seems like this extension assumes invoice == subscription. Which is fine. I'll just handle certain webhook events outside of this extension. But this is an area where it seems like we can decouple things nicely (FWIW)

Update comment for one-time payment

---

firestore-stripe-payments/functions/src/index.ts

Hi! This pull request is regarding the #489 issue that we are facing in my company.
:baby:  I have read the [contributing guidelines](https://github.com/stripe/stripe-firebase-extensions/blob/98c97775d54fb0be4601864b74d2fe5ce24dab83/CONTRIBUTING.md) and [code of conduct](url) but it is my first contribution so feel free to mention me any omission.
I don't know how to test but I followed [Stripe documentation](https://stripe.com/docs/payments/checkout/post-payment-invoices) and [Stripe API documentation](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-invoice_creation).
Added the param invoice_creation.enabled to checkout params, using invoice_creation prop (boolean).
Thanks!
fixes: https://github.com/invertase/stripe-firebase-extensions/issues/489

add invoice_creation prop for one-time payment

---

firestore-stripe-payments/functions/src/index.ts

Enables [free trials without payment details](https://stripe.com/docs/payments/checkout/free-trials) by passing `payment_method_collection` [parameter](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_method_collection) when creating `mode: 'subscription'` sessions.
fixes: #476

feat(firestore-stripe-payments): Support `payment_method_collection` parameter

---

firestore-stripe-payments/functions/src/index.ts

Resolves #551
Example usage to create a portal link that asks the customer to confirm an amendment to the price and/or quanity of a subscription:
```ts
import { getFunctions, httpsCallable } from 'firebase/functions';
const flow_data = {
type: 'subscription_update_confirm',
subscription_update_confirm: {
subscription: 'sub_XXXXXX',
items: [
{ id: 'si_XXXXXX', quantity: 4, price: 'price_XXXXXX' },
],
},
};
const portalLinkUrl = (await httpsCallable(getFunctions(app), 'createPortalLink')({ flow_data })).data.url;
```

Support `flow_data` parameter in `createPortalLink` function

---

firestore-stripe-payments/README.md

Hi team at Stripe!
Using this command from the [firebase docs](https://firebase.google.com/products/extensions/stripe-firestore-stripe-payments) does not seem to work for me:
```
firebase ext:install stripe/firestore-stripe-payments --local --project=projectId_or_alias
```
I wanted to open this because it caused some headaches until I found the error has to do with the version ref not being supplied with that command:  https://github.com/stripe/stripe-firebase-extensions/issues/394
I presume this would be a temporary solution, but should hopefully give other devs more info when trying to set up things via the CLI. The firebase CLI should theoretically be able to pull the version in the payload shown when running the command in debug mode:
``` …
```

update readme with CLI usage and local Webhook documentation
